version: '3'

services:
  mongo-db:
    image: mongo
    ports:
      - 27017:27017

  client-app:
    build: ./gomoku-react
    environment:
      - REACT_APP_API_HOST=http://localhost:8080
    volumes:
      - ./gomoku-react/src:/gomoku-react/src
      - ./gomoku-react/public:/gomoku-react/public
    ports:
      - 3000:3000

  server-app:
    build: ./gomoku-service
    environment:
      - dbURI=mongodb://mongo-db:27017
    volumes:
      - ./gomoku-service/src:/gomoku-service/src
    ports:
      - 8080:8080